# Azure DevOps Pipeline: Session Tracking
# Automatically generates session documentation on pushes to feature branches

trigger:
  branches:
    include:
      - 'feature/*'
      - 'bugfix/*'
      - 'project/*'
  paths:
    exclude:
      - 'docs/**'
      - '*.md'
      - '.github/**'

pr: none

pool:
  vmImage: 'windows-latest'

variables:
  - name: sessionDir
    value: 'docs/context'

steps:
  - checkout: self
    persistCredentials: true
    clean: true

  - task: PowerShell@2
    displayName: 'Check for Session File'
    inputs:
      targetType: 'inline'
      script: |
        $branch = $env:BUILD_SOURCEBRANCHNAME
        $today = Get-Date -Format "yyyyMMdd"
        $sessionPattern = "$(sessionDir)/session-$today-*-$branch.md"
        
        Write-Host "Looking for session file: $sessionPattern"
        
        $sessionFile = Get-ChildItem -Path $sessionPattern -ErrorAction SilentlyContinue | Select-Object -First 1
        
        if ($sessionFile) {
          Write-Host "##vso[task.setvariable variable=SESSION_EXISTS]true"
          Write-Host "##vso[task.setvariable variable=SESSION_FILE]$($sessionFile.FullName)"
          Write-Host "Session file found: $($sessionFile.Name)"
        } else {
          Write-Host "##vso[task.setvariable variable=SESSION_EXISTS]false"
          Write-Host "No session file found for today"
        }

  - task: PowerShell@2
    displayName: 'Update Session with Commit Info'
    condition: eq(variables['SESSION_EXISTS'], 'true')
    inputs:
      targetType: 'inline'
      script: |
        $sessionFile = $env:SESSION_FILE
        $commitMsg = $env:BUILD_SOURCEVERSIONMESSAGE
        $commitSha = $env:BUILD_SOURCEVERSION.Substring(0, 7)
        $timestamp = Get-Date -Format "yyyy-MM-dd HH:mm"
        
        Write-Host "Updating session file: $sessionFile"
        Write-Host "Commit: $commitSha - $commitMsg"
        
        # Read current session content
        $content = Get-Content -Path $sessionFile -Raw
        
        # Add commit to Files Modified section if not already there
        $commitEntry = "- $timestamp - $commitSha - $commitMsg"
        
        if ($content -notmatch [regex]::Escape($commitSha)) {
          # Find Files Modified section and append
          if ($content -match "## Files Modified\s*\n") {
            $content = $content -replace "(## Files Modified\s*\n)", "`$1$commitEntry`n"
          } else {
            # Add section if it doesn't exist
            $content += "`n`n## Files Modified`n$commitEntry`n"
          }
          
          Set-Content -Path $sessionFile -Value $content -Encoding UTF8
          Write-Host "Session updated with commit information"
        } else {
          Write-Host "Commit already recorded in session"
        }

  - task: PowerShell@2
    displayName: 'Create Session Summary from Commits'
    condition: eq(variables['SESSION_EXISTS'], 'false')
    inputs:
      targetType: 'inline'
      script: |
        $branch = $env:BUILD_SOURCEBRANCHNAME
        $today = Get-Date -Format "yyyyMMdd"
        $time = Get-Date -Format "HHmm"
        $timestamp = Get-Date -Format "yyyy-MM-dd HH:mm"
        $sessionFile = "$(sessionDir)/session-$today-$time-$branch.md"
        
        # Ensure directory exists
        if (-not (Test-Path "$(sessionDir)")) {
          New-Item -ItemType Directory -Path "$(sessionDir)" -Force | Out-Null
        }
        
        # Get recent commits
        $commits = git log --oneline -n 5 --pretty=format:"%h - %s"
        
        # Create basic session file
        $sessionContent = @"
# Session Summary: $today - $branch

## Status: Automated (Generated by Pipeline)

## Goals
- Automated session tracking from pipeline

## Completed
- Commits pushed to branch

## Recent Commits
$commits

## Key Decisions
- (Add manual updates as needed)

## Open Items
- (Add manual updates as needed)

## Files Modified
- See commit history

## Notes
- Session auto-created: $timestamp
- This was generated automatically by Azure DevOps pipeline
- Update manually with additional context
"@
        
        Set-Content -Path $sessionFile -Value $sessionContent -Encoding UTF8
        Write-Host "##vso[task.setvariable variable=SESSION_CREATED]true"
        Write-Host "Created automated session: $sessionFile"

  - task: PowerShell@2
    displayName: 'Commit Session Updates'
    condition: or(eq(variables['SESSION_EXISTS'], 'true'), eq(variables['SESSION_CREATED'], 'true'))
    inputs:
      targetType: 'inline'
      script: |
        # Configure git
        git config user.name "Azure DevOps Pipeline"
        git config user.email "pipeline@azuredevops.com"
        
        # Stage session files
        git add docs/context/*.md
        
        # Check if there are changes
        $status = git status --porcelain
        if ($status) {
          git commit -m "chore: update session tracking [skip ci]"
          git push origin HEAD:$env:BUILD_SOURCEBRANCHNAME
          Write-Host "Session updates committed and pushed"
        } else {
          Write-Host "No session changes to commit"
        }
    env:
      SYSTEM_ACCESSTOKEN: $(System.AccessToken)
