# Azure DevOps Pipeline: Work Summary Assistant
# Manual trigger to help generate work summaries

trigger: none

pr: none

pool:
  vmImage: 'windows-latest'

parameters:
  - name: topic
    displayName: 'Work Summary Topic'
    type: string
    default: 'work-progress'
  
  - name: commitCount
    displayName: 'Number of Commits to Analyze'
    type: number
    default: 10

variables:
  - name: branch
    value: $[replace(variables['Build.SourceBranch'], 'refs/heads/', '')]

steps:
  - checkout: self
    persistCredentials: true
    clean: true

  - task: PowerShell@2
    displayName: 'Collect Git Information'
    inputs:
      targetType: 'inline'
      script: |
        Write-Host "Analyzing branch: $(branch)"
        Write-Host "Topic: ${{ parameters.topic }}"
        Write-Host "Commits to analyze: ${{ parameters.commitCount }}"
        
        # Get recent commits
        Write-Host "`n=== Recent Commits ==="
        $commits = git log --oneline -n ${{ parameters.commitCount }}
        Write-Host $commits
        
        # Get changed files
        Write-Host "`n=== Changed Files ==="
        $changedFiles = git diff --name-status HEAD~${{ parameters.commitCount }}..HEAD
        Write-Host $changedFiles
        
        # Get diff statistics
        Write-Host "`n=== Diff Statistics ==="
        $diffStats = git diff --stat HEAD~${{ parameters.commitCount }}..HEAD
        Write-Host $diffStats
        
        # Get current status
        Write-Host "`n=== Current Status ==="
        $status = git status --short
        Write-Host $status
        
        # Save to variables
        Write-Host "##vso[task.setvariable variable=GIT_COMMITS]$commits"
        Write-Host "##vso[task.setvariable variable=GIT_FILES]$changedFiles"
        Write-Host "##vso[task.setvariable variable=GIT_STATS]$diffStats"

  - task: PowerShell@2
    displayName: 'Generate Work Summary Template'
    inputs:
      targetType: 'inline'
      script: |
        $branch = "$(branch)"
        $topic = "${{ parameters.topic }}"
        $today = Get-Date -Format "yyyy-MM-dd"
        $time = Get-Date -Format "HHmm"
        
        $workFolder = "docs/work/$branch"
        $contextFolder = "$workFolder/context"
        $summaryFile = "$contextFolder/$today-$time-$topic.md"
        
        # Ensure directory exists
        if (-not (Test-Path $contextFolder)) {
          New-Item -ItemType Directory -Path $contextFolder -Force | Out-Null
          Write-Host "Created context directory: $contextFolder"
        }
        
        # Create work summary template
        $summaryContent = @"
# Work Summary: $topic

**Date**: $today
**Branch**: ``$branch``

## Objective

[What we set out to accomplish - FILL IN]

## What Was Accomplished

[Detailed description of work done, organized by area/component]

### Recent Commits
``````
$(GIT_COMMITS)
``````

### Files Changed
``````
$(GIT_FILES)
``````

### Statistics
``````
$(GIT_STATS)
``````

## Key Decisions

[Important choices made and rationale - FILL IN]

## Challenges & Solutions

[Problems encountered and how they were solved - FILL IN]

## Code Quality

[Notes on testing, code review, documentation - FILL IN]

## Files Modified

[List of key files changed with brief description - see commits above]

## Next Steps

[What remains to be done, organized by priority - FILL IN]

1. [Priority 1]
2. [Priority 2]
3. [Priority 3]

## References

- Session files: ``docs/context/session-*-$branch.md``
- Implementation plan: ``$workFolder/implementation-plan.md``
- Related ADRs: [List ADR numbers]

## Notes

- This template was generated by Azure DevOps pipeline
- Review and fill in the sections marked [FILL IN]
- Use this as a starting point for detailed work summary

---

**Generated**: $today $time  
**Pipeline Run**: $(Build.BuildNumber)
"@
        
        Set-Content -Path $summaryFile -Value $summaryContent -Encoding UTF8
        Write-Host "##vso[task.setvariable variable=SUMMARY_FILE]$summaryFile"
        Write-Host "Created work summary template: $summaryFile"

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Work Summary Template'
    inputs:
      PathtoPublish: '$(SUMMARY_FILE)'
      ArtifactName: 'work-summary'
      publishLocation: 'Container'

  - task: PowerShell@2
    displayName: 'Generate Copilot Prompt'
    inputs:
      targetType: 'inline'
      script: |
        $summaryFile = "$(SUMMARY_FILE)"
        $branch = "$(branch)"
        $topic = "${{ parameters.topic }}"
        
        $prompt = @"
Please help me complete the work summary that was generated by the pipeline.

**File**: ``$summaryFile``
**Branch**: $branch
**Topic**: $topic

The template has been pre-populated with git information (commits, changed files, statistics).

Please help me:

1. Review the git information included in the template
2. Fill in the sections marked [FILL IN]:
   - **Objective**: What was the goal of this work?
   - **What Was Accomplished**: Detailed description of work done
   - **Key Decisions**: Important choices and rationale
   - **Challenges & Solutions**: Problems faced and how solved
   - **Code Quality**: Testing, review, documentation notes
   - **Next Steps**: What remains to be done (prioritized)

3. Ensure the summary is:
   - Specific and detailed enough for future reference
   - Captures the "why" not just the "what"
   - Documents any workarounds or technical debt
   - Includes concrete next steps

**Model Selection**: Use Claude Opus 4.5 for best quality.

Let's start by reviewing the commits and discussing what was accomplished.
"@
        
        Write-Host "`n=== Copilot Prompt ==="
        Write-Host $prompt
        Write-Host "`n====================="
        
        # Save prompt to file
        $promptFile = "$(SUMMARY_FILE).prompt.txt"
        Set-Content -Path $promptFile -Value $prompt -Encoding UTF8
        Write-Host "`nPrompt saved to: $promptFile"

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Copilot Prompt'
    inputs:
      PathtoPublish: '$(SUMMARY_FILE).prompt.txt'
      ArtifactName: 'copilot-prompt'
      publishLocation: 'Container'

  - task: PowerShell@2
    displayName: 'Commit Work Summary Template'
    inputs:
      targetType: 'inline'
      script: |
        # Configure git
        git config user.name "Azure DevOps Pipeline"
        git config user.email "pipeline@azuredevops.com"
        
        # Stage work summary
        git add "$(SUMMARY_FILE)"
        
        # Commit
        git commit -m "docs: add work summary template for ${{ parameters.topic }} [skip ci]"
        git push origin HEAD:$(branch)
        
        Write-Host "Work summary template committed and pushed"
    env:
      SYSTEM_ACCESSTOKEN: $(System.AccessToken)

  - task: PowerShell@2
    displayName: 'Pipeline Summary'
    inputs:
      targetType: 'inline'
      script: |
        Write-Host "`n=== Work Summary Pipeline Complete ==="
        Write-Host "Summary file created: $(SUMMARY_FILE)"
        Write-Host "Branch: $(branch)"
        Write-Host "Topic: ${{ parameters.topic }}"
        Write-Host ""
        Write-Host "Next steps:"
        Write-Host "1. Download the 'copilot-prompt' artifact"
        Write-Host "2. Open the prompt file"
        Write-Host "3. Paste into GitHub Copilot Chat"
        Write-Host "4. Work with Copilot to complete the summary"
        Write-Host "5. Edit the summary file: $(SUMMARY_FILE)"
        Write-Host "6. Commit the completed summary"
        Write-Host ""
        Write-Host "Alternatively, run locally:"
        Write-Host ".\scripts\New-WorkSummary.ps1 -Topic '${{ parameters.topic }}'"
